Macro3: Macro3.cpp
	g++ -o Macro3 Macro3.cpp

Macro2: Macro2.cpp
	g++ -o Macro2 Macro2.cpp

Macro2b: Macro2b.cpp
	g++ -o Macro2b Macro2b.cpp

Macro1b: Macro1b.cpp
	g++ -o Macro1b Macro1b.cpp

Macro1: Macro1.cpp
	g++ -o Macro1 Macro1.cpp

Typedef2: Typedef2.cpp
	g++ -o Typedef2 Typedef2.cpp

Typedef1: Typedef1.cpp
	g++ -o Typedef1 Typedef1.cpp

BitFlag1: BitFrag1.cpp
	g++ -o BitFlag1 BitFrag1.cpp

Cast2: Cast2.cpp
	g++ -o Cast2 Cast2.cpp

Cast1: Cast1.cpp
	g++ -o Cast1 Cast1.cpp

Explicit1: Explicit1.cpp IntArray.cpp
	g++ -o Explicit1 Explicit1.cpp IntArray.cpp

Assign2: Assign2.cpp
	g++ -o Assign2 Assign2.cpp

Assign1: Assign1.cpp
	g++ -o Assign1 Assign1.cpp

Temporary3b: Temporary3b.cpp 
	g++ -o Temporary3b Temporary3b.cpp

Temporary3: Temporary3.cpp 
	g++ -o Temporary3 Temporary3.cpp

Temporary2c: Temporary2c.cpp 
	g++ -o Temporary2c Temporary2c.cpp

Temporary2b: Temporary2b.cpp 
	g++ -o Temporary2b Temporary2b.cpp

Temporary2: Temporary2.cpp 
	g++ -o Temporary2 Temporary2.cpp

Temporary1: Temporary1.cpp 
	g++ -o Temporary1 Temporary1.cpp

Const3: Const3.cpp
	g++ -o Const3 Const3.cpp

Const2: Const2.cpp
	g++ -o Const2 Const2.cpp

StaticMember2d: StaticMember2d.cpp
	g++ -o StaticMember2d StaticMember2d.cpp

StaticMember2c: StaticMember2c.cpp
	g++ -o StaticMember2c StaticMember2c.cpp

StaticMember2b: StaticMember2b.cpp
	g++ -o StaticMember2b StaticMember2b.cpp

StaticMember2: StaticMember2.cpp
	g++ -o StaticMember2 StaticMember2.cpp

StaticMember1: StaticMember1.cpp Integer.cpp
	g++ -o StaticMember1 StaticMember1.cpp Integer.cpp