Exception5: Exception5.cpp
	g++ -o Exception5 Exception5.cpp

Exception1i: Exception1i.cpp FileException.cpp Exception.cpp 
	g++ -o Exception1i Exception1i.cpp FileException.cpp Exception.cpp 

Exception1h: Exception1h.cpp FileException.cpp Exception.cpp 
	g++ -o Exception1h Exception1h.cpp FileException.cpp Exception.cpp 

Exception4b: Exception4b.cpp
	g++ -o Exception4b Exception4b.cpp

Exception4: Exception4.cpp
	g++ -o Exception4 Exception4.cpp

Exception3: Exception3.cpp
	g++ -o Exception3 Exception3.cpp

Exception1g: Exception1g.cpp
	g++ -o Exception1g Exception1g.cpp

Exception2: Exception2.cpp
	g++ -o Exception2 Exception2.cpp

Exception1f: Exception1f.cpp
	g++ -o Exception1f Exception1f.cpp

Exception1e: Exception1e.cpp
	g++ -o Exception1e Exception1e.cpp

Exception1d: Exception1d.cpp
	g++ -o Exception1d Exception1d.cpp

Exception1c: Exception1c.cpp
	g++ -o Exception1c Exception1c.cpp

Exception1b: Exception1b.cpp
	g++ -o Exception1b Exception1b.cpp

Exception1: Exception1.cpp
	g++ -o Exception1 Exception1.cpp