Operator1: Operator1.cpp IntArray.cpp IntArray.h
	g++ -o Operator1 Operator1.cpp IntArray.cpp IntArray.h

Copy1: Copy1.cpp IntArray.cpp IntArray.h
	g++ -o Copy1 Copy1.cpp IntArray.cpp IntArray.h

Copy1b: Copy1b.cpp IntArray.cpp IntArray.h
	g++ -o Copy1b Copy1b.cpp IntArray.cpp IntArray.h

Class2: Class2.cpp Test.cpp Test.h
	g++ -o Class2 Class2.cpp Test.cpp Test.h

Destructor1: Destructor1.cpp 
	g++ -o Destructor1 Destructor1.cpp 

Constructor2: Constructor2.cpp 
	g++ -o Constructor2 Constructor2.cpp 

Constructor1: Constructor1.cpp 
	g++ -o Constructor1 Constructor1.cpp 

Class1b: Class1b.cpp
	g++ -o Class1b Class1b.cpp

Class1: Class1.cpp
	g++ -o Class1 Class1.cpp