Namespace4c: Namespace4c.cpp
	g++ -o Namespace4c Namespace4c.cpp

Namespace4b: Namespace4b.cpp
	g++ -o Namespace4b Namespace4b.cpp

Namespace4: Namespace4.cpp
	g++ -o Namespace4 Namespace4.cpp

Namespace3: Namespace3.cpp
	g++ -o Namespace3 Namespace3.cpp

Namespace2: Namespace2.cpp
	g++ -o Namespace2 Namespace2.cpp

Namespace1: Namespace1.cpp
	g++ -o Namespace1 Namespace1.cpp

Input2: Input2.cpp
	g++ -o Input2 Input2.cpp

File6: File6.cpp
	g++ -o File6 File6.cpp

File5b: File5b.cpp
	g++ -o File5b File5b.cpp

File5: File5.cpp
	g++ -o File5 File5.cpp

File4: File4.cpp
	g++ -o File4 File4.cpp

File3b: File3b.cpp
	g++ -o File3b File3b.cpp

File3: File3.cpp
	g++ -o File3 File3.cpp

File2: File2.cpp
	g++ -o File2 File2.cpp

File1: File1.cpp
	g++ -o File1 File1.cpp

StringStream2: StringStream2.cpp
	g++ -o StringStream2 StringStream2.cpp

StringStream1: StringStream1.cpp
	g++ -o StringStream1 StringStream1.cpp

String4: String4.cpp
	g++ -o String4 String4.cpp

String3: String3.cpp
	g++ -o String3 String3.cpp