Bool2: Bool2.cpp
	g++ -o Bool2 Bool2.cpp

Bool1: Bool1.cpp
	g++ -o Bool1 Bool1.cpp

Overload1: Overload1.cpp
	g++ -o Overload1 Overload1.cpp

NumericalError1b: NumericalError1b.cpp
	g++ -o NumericalError1b NumericalError1b.cpp

NumericalError1: NumericalError1.cpp
	g++ -o NumericalError1 NumericalError1.cpp

Math1: Math1.cpp
	g++ -o Math1 Math1.cpp

Rand1c: Rand1c.cpp
	g++ -o Rand1c Rand1c.cpp

Rand1b: Rand1b.cpp
	g++ -o Rand1b Rand1b.cpp

Rand1: Rand1.cpp
	g++ -o Rand1 Rand1.cpp

Include1: Include1.cpp Include1.h
	g++ -o Include1 Include1.cpp

Proto2: Proto2.cpp
	g++ -o Proto2 Proto2.cpp

Proto2b: Proto2b.cpp
	g++ -o Proto2b Proto2b.cpp

Proto1: Proto1.cpp
	g++ -o Proto1 Proto1.cpp

String2: String2.cpp
	g++ -o String2 String2.cpp

String1b: String1b.cpp
	g++ -o String1b String1b.cpp

String1: String1.cpp
	g++ -o String1 String1.cpp

Char1: Char1.cpp
	g++ -o Char1 Char1.cpp

Ref1: Ref1.cpp
	g++ -o Ref1 Ref1.cpp

Ref1b: Ref1b.cpp
	g++ -o Ref1b Ref1b.cpp