Vector2: Vector2.cpp
	g++ -o Vector2 Vector2.cpp

Vector1: Vector1.cpp
	g++ -o Vector1 Vector1.cpp

Template5: Template5.cpp
	g++ -o Template5 Template5.cpp

ClassTemplate1: ClassTemplate1.cpp
	g++ -o ClassTemplate1 ClassTemplate1.cpp

Template4: Template4.cpp
	g++ -o Template4 Template4.cpp

Template3: Template3.cpp
	g++ -o Template3 Template3.cpp

Template2: Template2.cpp
	g++ -o Template2 Template2.cpp

Template1b: Template1b.cpp
	g++ -o Template1b Template1b.cpp

Template1: Template1.cpp
	g++ -o Template1 Template1.cpp